<?php

/**
 * @file
 * Contains mbta.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function mbta_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the mbta module.
    case 'help.page.mbta':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t("Connect the the MBTA's api to show real time schedules/routes.") . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function mbta_theme($existing, $type, $theme, $path) {
  return [
    'mbta_routes' => [
      'variables' => ['items' => null, 'heading' => null]
    ],
  ];
}
